version: '3.3'
services:
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_DATABASE: 'db_api'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
